services:
  radarr4k:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr4k
    stop_grace_period: 20s
    networks:
      net.internal: {}
      net_overlay: {}
    restart: always
    mem_limit: 1g
    volumes:
      - /mnt/cache/appdata/radarr4k:/config
      - /mnt/tank/media:/data
      - /mnt/cache/downloads:/downloads
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      traefik.enable: 'true'
      traefik.http.routers.radarr4k.entryPoints: 'https'
      traefik.http.routers.radarr4k.middlewares: 'allow-local@file'
      traefik.http.services.radarr4k.loadbalancer.server.port: '7878'

networks:
  net.internal:
    external: true
  net_overlay:
    external: true


