from __future__ import annotations

import stat
from pathlib import Path

import pytest

from homelab import op_secrets
from homelab.modules import pve_backup


def test_secret_name_for_pbs_password_var() -> None:
    assert (
        pve_backup.secret_name_for_pbs_password_var("PBS_BACKUP_MAIN_PASSWORD")
        == "pbs-backup-main"
    )
    assert (
        pve_backup.secret_name_for_pbs_password_var("PBS_BACKUP_CINCI_PASSWORD")
        == "pbs-backup-cinci"
    )


def test_secret_name_for_pbs_password_var_rejects_invalid_name() -> None:
    with pytest.raises(op_secrets.OpSecretsError):
        pve_backup.secret_name_for_pbs_password_var("BACKUP_MAIN_PASSWORD")


def test_write_pbs_tokens_file_dedupes_storage_passwords(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    class FakeRegistry:
        def get(self, host: str, key: str, default: object = None) -> object:
            assert host == "osiris"
            assert key == "pve-backup.pbs_setup.storages"
            return [
                {"name": "backup-main"},
                {"name": "backup-main-copy", "password_var": "PBS_BACKUP_MAIN_PASSWORD"},
                {"name": "backup-cinci"},
            ]

    monkeypatch.setattr(pve_backup, "default_registry", lambda root: FakeRegistry())
    monkeypatch.setattr(
        pve_backup,
        "read_pbs_password",
        lambda root, password_var: f"value for {password_var}",
    )

    destination = tmp_path / "pbs-tokens.env"
    pve_backup.write_pbs_tokens_file(tmp_path, "osiris", destination)

    assert destination.read_text(encoding="utf-8") == (
        "# PBS storage passwords\n"
        "# Generated by pve-backup deploy from 1Password-backed secrets.\n"
        "\n"
        "PBS_BACKUP_MAIN_PASSWORD='value for PBS_BACKUP_MAIN_PASSWORD'\n"
        "PBS_BACKUP_CINCI_PASSWORD='value for PBS_BACKUP_CINCI_PASSWORD'\n"
    )
    assert stat.S_IMODE(destination.stat().st_mode) == 0o600


def _storage_registry(storages: list[dict[str, object]]) -> object:
    class FakeRegistry:
        def get(self, host: str, key: str, default: object = None) -> object:
            if key == "pve-backup.pbs_setup.storages":
                return storages
            if key == "pve-backup.pbs_setup.jobs":
                return []
            return default

    return FakeRegistry()


def test_build_standalone_backup_plans_emits_encryption_flag(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    storages = [
        {
            "name": "backup-local",
            "server": "xur",
            "datastore": "backup",
            "username": "u@pbs",
            "fingerprint": "aa:bb",
            "password_var": "PBS_BACKUP_MAIN_PASSWORD",
            "encryption": True,
        },
        {
            "name": "backup-plain",
            "server": "cinci",
            "datastore": "backup",
            "username": "v@pbs",
            "fingerprint": "cc:dd",
            "password_var": "PBS_BACKUP_CINCI_PASSWORD",
        },
    ]
    monkeypatch.setattr(
        pve_backup, "default_registry", lambda root: _storage_registry(storages)
    )
    build_dir = tmp_path / "build"
    build_dir.mkdir()
    pve_backup.build_standalone_backup_plans(tmp_path, "ace", build_dir)

    text = (build_dir / "storage-plan.conf").read_text(encoding="utf-8")
    assert "STORAGE_0_ENCRYPTION='true'" in text
    assert "STORAGE_1_ENCRYPTION='false'" in text


def test_host_has_encrypted_storage(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        pve_backup,
        "default_registry",
        lambda root: _storage_registry([{"name": "s", "encryption": True}]),
    )
    assert pve_backup.host_has_encrypted_storage(tmp_path, "ace") is True

    monkeypatch.setattr(
        pve_backup,
        "default_registry",
        lambda root: _storage_registry([{"name": "s"}]),
    )
    assert pve_backup.host_has_encrypted_storage(tmp_path, "ace") is False
