"""pve-backup: remote installer (freender/homelab-ops#30).

`pvesh`/`pvesm`/`pct`/`proxmox-backup-client` are replaced by one in-memory PVE
node, and every absolute path is rebound under `tmp_path`, so each test asserts on
the resulting storages, jobs and files rather than on which commands ran.

What carries the risk, and what these pin:

* **A converged node writes nothing.** The live storages and jobs below are the
  JSON ace and osiris returned before the port; the bash rewrote all of them on
  every deploy, and an unchanged mtime is the canary's evidence.
* **A storage is never left undefined**: a failed recreate puts the old stanza and
  password back, and an existing encryption key is never replaced.
* **Every refusal comes before any write**, and **no staged credential survives
  any exit**.
* **Restore picks the newest snapshot that holds the archive** and never restarts
  a running container.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from homelab.modules import pve_backup
from homelab_install.context import InstallContext
from homelab_install.errors import InstallError

ROOT = Path(__file__).resolve().parents[1]
INSTALLER_PATH = ROOT / "pve-backup" / "scripts" / "install.py"

FINGERPRINT = "d6:93:fa:64:27:cb:0f:f2:1c:7d:66:4c:22:3b:a3:11:b7:80:ae:f4:3f:1b:3a:e6:6d"
KEY_FP = "68:4e:4a:f3:c1:f4:65:83:f9:f9:3c:14:83:d3:65:9a:b6:41:a2:4e:9d:f2:35:f3"
EXCLUDES = ["/var/log/journal", "/tmp"]

STORAGE_PLAN = f"""STORAGE_COUNT='1'
STORAGE_0_NAME='backup-local'
STORAGE_0_SERVER='xur.freender.internal'
STORAGE_0_DATASTORE='backup'
STORAGE_0_NAMESPACE='freender'
STORAGE_0_USERNAME='pve-backup@pbs'
STORAGE_0_FINGERPRINT='{FINGERPRINT}'
STORAGE_0_PASSWORD_VAR='PBS_BACKUP_MAIN_PASSWORD'
STORAGE_0_ENCRYPTION='true'
"""

TOKENS = """# PBS storage passwords
# Generated by pve-backup deploy from 1Password-backed secrets.

PBS_BACKUP_MAIN_PASSWORD='s3cr'"'"'et'
"""
PASSWORD = "s3cr'et"


def job_plan(vmid: str = "", exclude: str = "105", paths: list[str] | None = None) -> str:
    paths = EXCLUDES if paths is None else paths
    lines = [
        "JOB_COUNT='1'",
        "JOB_0_SCHEDULE='*-*-* 23:00:00'",
        "JOB_0_STORAGE='backup-local'",
        f"JOB_0_VMID='{vmid}'",
        f"JOB_0_EXCLUDE='{exclude}'",
        "JOB_0_COMPRESS='zstd'",
        "JOB_0_MODE='snapshot'",
        "JOB_0_NOTES_TEMPLATE='{{guestname}}'",
        "JOB_0_NOTIFICATION_MODE='notification-system'",
        "JOB_0_PRUNE_BACKUPS='keep-all=1'",
        "JOB_0_ENABLED='1'",
        "JOB_0_FLEECING='0'",
        f"JOB_0_EXCLUDE_PATH_COUNT='{len(paths)}'",
        *[f"JOB_0_EXCLUDE_PATH_{index}='{path}'" for index, path in enumerate(paths)],
    ]
    return "\n".join(lines) + "\n"


def restore_plan(
    enabled: bool = True, autostart: bool = False, keyfile: str = "/etc/homelab/pbs-encryption.key"
) -> str:
    return (
        "NAMESPACE='freender'\nBACKUP_ID='pve-standalone'\nARCHIVE_NAME='etc-pve'\n"
        f"ENCRYPT='true'\nKEYFILE='{keyfile}'\n"
        f"RESTORE_LXC_CONFIGS_ENABLED='{str(enabled).lower()}'\n"
        f"RESTORE_LXC_AUTOSTART='{str(autostart).lower()}'\n"
        "RESTORE_LXC_CONFIG_COUNT='1'\nDESTINATION_COUNT='2'\n"
        "DESTINATION_0_REPOSITORY='xur-sync@pbs@cinci.internal:backup'\n"
        "DESTINATION_1_REPOSITORY='osiris-backup@pbs@cottonwood.internal:backup'\n"
        "RESTORE_LXC_CONFIG_0_VMID='105'\n"
    )


def live_storage() -> dict:
    return {
        "storage": "backup-local",
        "type": "pbs",
        "content": "backup",
        "datastore": "backup",
        "digest": "08ab",
        "encryption-key": KEY_FP,
        "fingerprint": FINGERPRINT,
        "namespace": "freender",
        "prune-backups": "keep-all=1",
        "server": "xur.freender.internal",
        "shared": 1,
        "username": "pve-backup@pbs",
    }


def live_job() -> dict:
    return {
        "id": "9fe2a2c4",
        "type": "vzdump",
        "all": 1,
        "compress": "zstd",
        "enabled": 1,
        "exclude": "105",
        "exclude-path": list(EXCLUDES),
        "fleecing": {"enabled": 0},
        "mode": "snapshot",
        "next-run": 1789441200,
        "notes-template": "{{guestname}}",
        "notification-mode": "notification-system",
        "prune-backups": {"keep-all": 1},
        "schedule": "*-*-* 23:00:00",
        "storage": "backup-local",
    }


def load_installer():
    spec = importlib.util.spec_from_file_location("pve_backup_installer", INSTALLER_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    # Registered before exec: `@dataclass` resolves annotations through sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def options(argv: list[str]) -> dict[str, object]:
    values: dict[str, object] = {}
    for flag, value in zip(argv[::2], argv[1::2], strict=True):
        key = flag.removeprefix("--")
        if key == "exclude-path":
            values.setdefault(key, []).append(value)  # type: ignore[union-attr]
        else:
            values[key] = value
    return values


class Node:
    """One PVE node: storage.cfg entries, `.pw` files, vzdump jobs, containers, and
    the PBS datastores the restore step reads from."""

    def __init__(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        self.m = load_installer()
        self.tmp = tmp_path
        self.pve = tmp_path / "etc" / "pve"
        (self.pve / "priv" / "storage").mkdir(parents=True)
        for name, value in {
            "PERSISTENT_KEYFILE": str(tmp_path / "etc" / "homelab" / "pbs-encryption.key"),
            "STORAGE_CFG": str(self.pve / "storage.cfg"),
            "STORAGE_PRIV": str(self.pve / "priv" / "storage"),
            "PVE_DIR": str(self.pve),
            "RESTORE_ROOT": str(tmp_path / "tmp" / "pve-config-restore"),
            "RESTORE_OUTPUT": str(tmp_path / "var" / "pve-config-restore"),
        }.items():
            monkeypatch.setattr(self.m, name, value)
        monkeypatch.setattr(self.m, "_run", self)
        monkeypatch.setattr(self.m, "_which", lambda name: f"/usr/bin/{name}")
        monkeypatch.setattr(shutil, "chown", lambda *_args, **_kwargs: None)

        self.build = tmp_path / "build" / "osiris"
        self.build.mkdir(parents=True)
        self.storages: dict[str, dict] = {"backup-local": live_storage()}
        self.write_pw("backup-local", PASSWORD)
        (self.pve / "storage.cfg").write_text(
            "dir: local\n\tpath /var/lib/vz\n\npbs: backup-local\n\tdatastore backup\n"
            "\tserver xur.freender.internal\n\n",
            encoding="utf-8",
        )
        self.jobs: list[dict] = [live_job()]
        self.writes: list[list[str]] = []
        self.inactive: set[str] = set()
        self.add_error = ""
        self.running: set[str] = set()
        self.volumes = {"vm-flash:subvol-105-disk-0"}
        self.datastores: dict[str, list[dict]] = {}
        self.listing_error: dict[str, str] = {}
        self.envs: list[dict[str, str]] = []

    # --- fixtures ---

    def write_pw(self, name: str, password: str) -> None:
        (self.pve / "priv" / "storage" / f"{name}.pw").write_text(f"{password}\n")

    def stage(
        self,
        storage: str | None = STORAGE_PLAN,
        jobs: str | None = None,
        restore: str | None = None,
        tokens: str = TOKENS,
        key: bool = True,
    ) -> None:
        for name, text in (
            ("storage-plan.conf", storage),
            ("jobs-plan.conf", job_plan() if jobs is None else jobs),
            ("restore-plan.conf", restore),
        ):
            if text:
                (self.build / name).write_text(text, encoding="utf-8")
        (self.build / "pbs-tokens.env").write_text(tokens, encoding="utf-8")
        if key:
            (self.build / "pbs-encryption.key").write_bytes(b"KEY")

    def deploy(self, force: bool = False) -> None:
        ctx = InstallContext(
            host="osiris",
            script_dir=self.build.parent.parent,
            build_dir=self.build,
            env={},
            deploy_env={},
            file_map={},
            force_update=force,
        )
        self.m.install(ctx)

    # --- the fake commands ---

    def __call__(self, argv, **kwargs):
        handler = {
            "pvesh": self.pvesh,
            "pvesm": self.pvesm,
            "pct": self.pct,
            "proxmox-backup-client": self.client,
            "shred": self.shred,
        }[argv[0]]
        if argv[0] != "shred" and argv[1] not in ("get", "status", "path", "snapshots"):
            self.writes.append(list(argv))
        code, out, err = handler(argv, kwargs)
        return subprocess.CompletedProcess(argv, code, out, err)

    def shred(self, argv, _kwargs):
        Path(argv[-1]).unlink()
        return 0, "", ""

    def pvesh(self, argv, _kwargs):
        verb, path, *rest = argv[1:]
        if verb == "get" and path == "/storage":
            return 0, json.dumps(list(self.storages.values())), ""
        if verb == "get":
            return 0, json.dumps(self.jobs), ""
        values = options(rest)
        if verb == "create":
            self.jobs.append({"id": f"job{len(self.jobs)}", "type": "vzdump", **values})
            return 0, "", ""
        job = next(job for job in self.jobs if path.endswith(job["id"]))
        for key in str(values.pop("delete", "")).split(","):
            job.pop(key, None)
        job.update(values)
        return 0, "", ""

    def pvesm(self, argv, _kwargs):
        verb = argv[1]
        if verb == "status":
            return (1 if argv[-1] in self.inactive else 0), "", ""
        if verb == "path":
            return (0 if argv[-1] in self.volumes else 1), "", ""
        if verb == "remove":
            del self.storages[argv[2]]
            cfg = self.pve / "storage.cfg"
            cfg.write_text(cfg.read_text().split(f"pbs: {argv[2]}\n")[0])
            (self.pve / "priv" / "storage" / f"{argv[2]}.pw").unlink(missing_ok=True)
            return 0, "", ""
        name, rest = (argv[3], argv[4:]) if verb == "add" else (argv[2], argv[3:])
        if verb == "add" and self.add_error:
            return 255, "", self.add_error
        values = options(rest)
        if "password" in values:
            self.write_pw(name, str(values.pop("password")))
        if "encryption-key" in values:
            values["encryption-key"] = KEY_FP
        entry = self.storages.setdefault(name, {"storage": name, "type": "pbs"})
        for key in str(values.pop("delete", "")).split(","):
            entry.pop(key, None)
        entry.update(values)
        return 0, "", ""

    def pct(self, argv, _kwargs):
        if argv[1] == "status":
            state = "running" if argv[2] in self.running else "stopped"
            return 0, f"status: {state}\n", ""
        if argv[2] in self.running:
            return 255, "", "CT already running"
        self.running.add(argv[2])
        return 0, "", ""

    def client(self, argv, kwargs):
        repository = argv[argv.index("--repository") + 1]
        self.envs.append(kwargs["env"])
        if argv[1] == "snapshots":
            if repository in self.listing_error:
                return 1, "", self.listing_error[repository]
            return 0, json.dumps(self.datastores.get(repository, [])), ""
        target = Path(argv[4])
        lxc = target / "nodes" / "osiris" / "lxc"
        lxc.mkdir(parents=True)
        (lxc / "105.conf").write_text("onboot: 1\nrootfs: vm-flash:subvol-105-disk-0,size=8G\n")
        (target / "priv").mkdir()
        (target / "notifications.cfg").write_text("webhook: Alertmanager\n")
        (target / "priv" / "notifications.cfg").write_text("webhook: Alertmanager\n")
        return 0, "", ""


def snapshot(time: int, archive: str = "etc-pve") -> dict:
    return {
        "backup-type": "host",
        "backup-id": "pve-standalone",
        "backup-time": time,
        "files": [{"filename": f"{archive}.pxar.didx"}, {"filename": "index.json.blob"}],
    }


@pytest.fixture
def node(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Node:
    return Node(tmp_path, monkeypatch)


# --- reading ------------------------------------------------------------------


def test_read_env_parses_plans_tokens_and_op_inject_output(node: Node, tmp_path: Path) -> None:
    path = tmp_path / "mixed.env"
    path.write_text(
        "# comment\n\nA='it'\"'\"'s'\nB=\"quoted value\"\nC=\nD='{{guestname}}'\n",
        encoding="utf-8",
    )

    assert node.m.read_env(path) == {
        "A": "it's",
        "B": "quoted value",
        "C": "",
        "D": "{{guestname}}",
    }


def test_read_env_never_echoes_a_malformed_line(node: Node, tmp_path: Path) -> None:
    path = tmp_path / "bad.env"
    path.write_text("PBS_PASSWORD='hunter2\n", encoding="utf-8")

    with pytest.raises(InstallError) as caught:
        node.m.read_env(path)

    assert "hunter2" not in str(caught.value)


# --- converged ----------------------------------------------------------------


def test_a_converged_node_writes_nothing(node: Node) -> None:
    node.stage()
    cfg = (node.pve / "storage.cfg").read_text()

    node.deploy()

    assert node.writes == []
    assert (node.pve / "storage.cfg").read_text() == cfg


def test_force_rewrites_storage_and_job_once_each_without_changing_them(node: Node) -> None:
    node.stage()

    node.deploy(force=True)

    assert [write[:2] for write in node.writes] == [["pvesm", "set"], ["pvesh", "set"]]
    assert "--password" in node.writes[0]
    assert node.storages["backup-local"] == live_storage()


# --- storages -----------------------------------------------------------------


def test_a_drifted_username_is_set_without_resending_the_password(node: Node) -> None:
    node.storages["backup-local"]["username"] = "old@pbs"
    node.stage()

    node.deploy()

    assert node.storages["backup-local"]["username"] == "pve-backup@pbs"
    assert "--password" not in node.writes[0]


def test_a_rotated_password_is_sent(node: Node) -> None:
    node.write_pw("backup-local", "stale")
    node.stage()

    node.deploy()

    assert (node.pve / "priv" / "storage" / "backup-local.pw").read_text() == f"{PASSWORD}\n"
    assert len(node.writes) == 1


def test_an_emptied_namespace_is_deleted(node: Node) -> None:
    node.stage(storage=STORAGE_PLAN.replace("NAMESPACE='freender'", "NAMESPACE=''"))

    node.deploy()

    assert "namespace" not in node.storages["backup-local"]


def test_a_password_in_a_failed_set_is_not_reported(node: Node, monkeypatch) -> None:
    node.storages["backup-local"]["username"] = "old@pbs"
    node.stage()
    monkeypatch.setattr(
        node.m,
        "_run",
        lambda argv, **_kw: subprocess.CompletedProcess(
            argv,
            1 if argv[1] == "set" else 0,
            json.dumps(list(node.storages.values())) if argv[1] == "get" else "",
            f"bad value {PASSWORD}",
        ),
    )

    with pytest.raises(InstallError) as caught:
        node.deploy()

    assert PASSWORD not in str(caught.value)


def test_a_new_storage_is_added_with_its_prune_policy_then_encrypted(node: Node) -> None:
    node.storages.clear()
    node.stage()

    node.deploy()

    added = node.storages["backup-local"]
    assert added["prune-backups"] == "keep-all=1"
    assert added["encryption-key"] == KEY_FP
    assert [write[:2] for write in node.writes[:2]] == [["pvesm", "add"], ["pvesm", "set"]]


def test_an_existing_encryption_key_is_never_replaced(node: Node) -> None:
    node.storages["backup-local"]["encryption-key"] = "other"
    node.stage()

    node.deploy()

    assert node.storages["backup-local"]["encryption-key"] == "other"


def test_a_changed_server_recreates_the_storage(node: Node) -> None:
    node.storages["backup-local"]["server"] = "old.internal"
    node.stage()

    node.deploy()

    assert node.storages["backup-local"]["server"] == "xur.freender.internal"
    assert [write[1] for write in node.writes[:3]] == ["remove", "add", "set"]


def test_a_failed_recreate_puts_the_old_definition_and_password_back(node: Node) -> None:
    node.storages["backup-local"]["server"] = "old.internal"
    node.write_pw("backup-local", "old-password")
    node.add_error = "permission denied"
    node.stage()

    with pytest.raises(InstallError, match="permission denied"):
        node.deploy()

    cfg = (node.pve / "storage.cfg").read_text()
    assert cfg.count("pbs: backup-local") == 1
    assert cfg.endswith("pbs: backup-local\n\tdatastore backup\n\tserver xur.freender.internal\n\n")
    assert (node.pve / "priv" / "storage" / "backup-local.pw").read_text() == "old-password\n"


def test_an_unreachable_server_is_left_for_the_next_deploy(node: Node) -> None:
    node.storages.clear()
    node.add_error = "error fetching datastores - Can't connect to cinci.internal:8007"
    node.stage()

    node.deploy()

    assert "backup-local" not in node.storages


def test_the_keyfile_is_installed_at_600_and_not_rewritten_when_unchanged(node: Node) -> None:
    node.stage()
    node.deploy()
    keyfile = Path(node.m.PERSISTENT_KEYFILE)
    assert keyfile.read_bytes() == b"KEY"
    assert keyfile.stat().st_mode & 0o777 == 0o600
    assert keyfile.parent.stat().st_mode & 0o777 == 0o700
    mtime = keyfile.stat().st_mtime_ns

    node.stage()
    node.deploy()

    assert keyfile.stat().st_mtime_ns == mtime


# --- jobs ---------------------------------------------------------------------


def test_a_new_job_is_created_in_one_call(node: Node) -> None:
    node.jobs.clear()
    node.stage()

    node.deploy()

    assert len(node.writes) == 1
    job = node.jobs[0]
    assert job["exclude-path"] == EXCLUDES
    assert (job["all"], job["exclude"], job["fleecing"]) == ("1", "105", "0")


def test_a_drifted_schedule_updates_the_same_job(node: Node) -> None:
    node.jobs[0]["schedule"] = "*-*-* 01:00:00"
    node.stage()

    node.deploy()

    assert len(node.jobs) == 1
    assert node.jobs[0]["schedule"] == "*-*-* 23:00:00"


def test_an_emptied_exclude_path_list_is_deleted(node: Node) -> None:
    node.stage(jobs=job_plan(paths=[]))

    node.deploy()

    assert "exclude-path" not in node.jobs[0]


def test_a_vmid_job_drops_all_and_exclude(node: Node) -> None:
    node.jobs[0].update({"vmid": "105", "exclude": ""})
    node.stage(jobs=job_plan(vmid="105", exclude=""))

    node.deploy()

    assert "all" not in node.jobs[0]
    assert "exclude" not in node.jobs[0]
    assert node.writes[0][-2:] == ["--delete", "all,exclude"]


def test_a_job_on_an_inactive_storage_is_skipped(node: Node) -> None:
    node.jobs.clear()
    node.inactive.add("backup-local")
    node.stage()

    node.deploy()

    assert node.jobs == []


# --- refusals and secrets -----------------------------------------------------


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"tokens": "# empty\n"}, "PBS_BACKUP_MAIN_PASSWORD"),
        ({"key": False}, "keyfile was not staged"),
        ({"jobs": job_plan(vmid="105", exclude="105")}, "both vmid and exclude"),
        (
            {"storage": STORAGE_PLAN.replace("STORAGE_0_USERNAME='pve-backup@pbs'\n", "")},
            "missing STORAGE_0_USERNAME",
        ),
        (
            {"storage": STORAGE_PLAN.replace("ENCRYPTION='true'", "ENCRYPTION='yes'")},
            "true or false",
        ),
        ({"restore": restore_plan().replace("VMID='105'", "VMID='10 5'")}, "invalid LXC VMID"),
    ],
)
def test_every_refusal_comes_before_any_write_and_destroys_secrets(
    node: Node, kwargs: dict, message: str
) -> None:
    node.storages.clear()
    node.jobs.clear()
    node.stage(**kwargs)
    (node.build / "pbs-0.env").write_text("PBS_PASSWORD=x\n")

    with pytest.raises(InstallError, match=message):
        node.deploy()

    assert node.writes == []
    assert not Path(node.m.PERSISTENT_KEYFILE).exists()
    assert sorted(path.name for path in node.build.iterdir() if "pbs" in path.name) == []


def test_staged_secrets_are_destroyed_after_a_successful_deploy(node: Node) -> None:
    node.stage()
    (node.build / "pbs-1.env").write_text("PBS_PASSWORD=x\n")

    node.deploy()

    assert {path.name for path in node.build.iterdir()} == {"storage-plan.conf", "jobs-plan.conf"}


def test_a_node_with_no_plans_does_nothing(node: Node) -> None:
    node.deploy()

    assert node.writes == []


# --- restore ------------------------------------------------------------------


def restore_node(node: Node, enabled: bool = True, autostart: bool = False) -> None:
    node.datastores["xur-sync@pbs@cinci.internal:backup"] = [
        snapshot(1789273805),
        snapshot(1789360205),
        snapshot(1789400000, archive="other"),
    ]
    node.stage(restore=restore_plan(enabled, autostart, keyfile=node.m.PERSISTENT_KEYFILE))
    (node.build / "pbs-0.env").write_text('PBS_PASSWORD="pw0"\nPBS_FINGERPRINT="aa"\n')
    (node.build / "pbs-1.env").write_text('PBS_PASSWORD="pw1"\n')


def test_restore_is_skipped_when_every_listed_config_exists(node: Node) -> None:
    (node.pve / "nodes" / "osiris" / "lxc").mkdir(parents=True)
    (node.pve / "nodes" / "osiris" / "lxc" / "105.conf").write_text("x")
    restore_node(node)

    node.deploy()

    assert node.envs == []


def test_restore_is_skipped_without_force_when_lxc_restore_is_off(node: Node) -> None:
    restore_node(node, enabled=False)

    node.deploy()

    assert node.envs == []


def test_restore_fetches_the_newest_snapshot_that_holds_the_archive(node: Node) -> None:
    restore_node(node)

    node.deploy()

    restore_call = next(write for write in node.writes if write[1] == "restore")
    assert restore_call[2] == "host/pve-standalone/2026-09-14T04:30:05Z"
    assert restore_call[-2:] == ["--keyfile", node.m.PERSISTENT_KEYFILE]
    assert node.envs[-1]["PBS_PASSWORD"] == "pw0"
    live = (node.pve / "nodes" / "osiris" / "lxc" / "105.conf").read_text()
    assert "onboot: 0" in live
    assert (node.pve / "notifications.cfg").read_text() == "webhook: Alertmanager\n"
    assert (Path(node.m.RESTORE_OUTPUT) / "latest" / "priv" / "notifications.cfg").is_file()
    assert not Path(node.m.RESTORE_ROOT).exists()
    assert not (node.build / "lxc-105.conf").exists()


def test_a_failed_listing_is_reported_and_the_next_destination_tried(
    node: Node, capsys: pytest.CaptureFixture[str]
) -> None:
    restore_node(node)
    node.listing_error["xur-sync@pbs@cinci.internal:backup"] = "authentication failed"
    node.datastores["osiris-backup@pbs@cottonwood.internal:backup"] = [snapshot(1789360205)]

    node.deploy()

    assert "authentication failed" in capsys.readouterr().out
    assert node.envs[-1]["PBS_PASSWORD"] == "pw1"


def test_no_destination_restoring_fails_the_deploy(node: Node) -> None:
    restore_node(node)
    node.datastores.clear()

    with pytest.raises(InstallError, match="No configured PBS destination"):
        node.deploy()


def test_autostart_does_not_start_a_running_container_under_force(node: Node) -> None:
    (node.pve / "nodes" / "osiris" / "lxc").mkdir(parents=True)
    (node.pve / "nodes" / "osiris" / "lxc" / "105.conf").write_text("x")
    node.running.add("105")
    restore_node(node, autostart=True)

    node.deploy(force=True)

    assert not any(write[:2] == ["pct", "start"] for write in node.writes)
    assert "onboot: 1" in (node.pve / "nodes" / "osiris" / "lxc" / "105.conf").read_text()


def test_autostart_starts_a_stopped_restored_container(node: Node) -> None:
    restore_node(node, autostart=True)

    node.deploy()

    assert "105" in node.running


def test_a_config_referencing_a_missing_volume_is_refused(node: Node) -> None:
    node.volumes.clear()
    restore_node(node)

    with pytest.raises(InstallError, match="missing volume: vm-flash:subvol-105-disk-0"):
        node.deploy()

    assert not (node.pve / "nodes" / "osiris" / "lxc" / "105.conf").exists()


def test_prepared_config_appends_onboot_when_absent(node: Node, tmp_path: Path) -> None:
    source = tmp_path / "101.conf"
    source.write_text("arch: amd64\n")

    assert node.m.prepared_config(source, autostart=False) == "arch: amd64\n\nonboot: 0\n"
    assert node.m.prepared_config(source, autostart=True) == "arch: amd64\n"


# --- orchestrator -------------------------------------------------------------


def test_the_orchestrator_stages_the_python_installer(tmp_path: Path, monkeypatch) -> None:
    calls = []
    monkeypatch.setattr(
        pve_backup,
        "stage_and_run_remote_installer",
        lambda *args, **kwargs: calls.append((args, kwargs)),
    )
    monkeypatch.setattr(pve_backup, "build_standalone_backup_plans", lambda *_args: None)
    monkeypatch.setattr(pve_backup, "build_config_restore_plan", lambda *_args: None)
    monkeypatch.setattr(pve_backup, "HostConnection", lambda host: host)

    pve_backup.deploy_host(ROOT, "osiris", dry_run=False, force=False)

    args, kwargs = calls[0]
    assert args[4] == "scripts/install.py"
    assert kwargs["interpreter"] == "python3"
    assert INSTALLER_PATH.is_file()


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"storage": STORAGE_PLAN + "garbage\n"}, "malformed line"),
        ({"storage": STORAGE_PLAN.replace("COUNT='1'", "COUNT='one'")}, "non-negative integer"),
        (
            {"storage": STORAGE_PLAN.replace("SERVER='xur.freender.internal'", "SERVER=''")},
            "STORAGE_0_SERVER is empty",
        ),
        (
            {"jobs": job_plan().replace("STORAGE='backup-local'", "STORAGE=''")},
            "missing its schedule or storage",
        ),
        (
            {"restore": restore_plan().replace("BACKUP_ID='pve-standalone'", "BACKUP_ID=''")},
            "BACKUP_ID or ARCHIVE_NAME",
        ),
        (
            {"restore": restore_plan().replace("CONFIG_COUNT='1'", "CONFIG_COUNT='0'")},
            "lists no VMIDs",
        ),
        (
            {"restore": restore_plan().replace("DESTINATION_COUNT='2'", "DESTINATION_COUNT='0'")},
            "no PBS destinations",
        ),
        ({"storage": None, "restore": restore_plan(), "key": False}, "keyfile missing"),
    ],
)
def test_malformed_plans_are_refused(node: Node, kwargs: dict, message: str) -> None:
    node.stage(**kwargs)

    with pytest.raises(InstallError, match=message):
        node.deploy()

    assert node.writes == []


def test_a_missing_command_is_refused(node: Node, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(node.m, "_which", lambda name: None if name == "pvesh" else name)
    node.stage()

    with pytest.raises(InstallError, match="pvesh command not found"):
        node.deploy()


def test_a_missing_build_directory_is_refused(node: Node) -> None:
    shutil.rmtree(node.build)

    with pytest.raises(InstallError, match="missing build directory"):
        node.deploy()


def test_an_unencrypted_restore_needs_no_keyfile(node: Node) -> None:
    node.stage(
        storage=None,
        jobs="JOB_COUNT='0'\n",
        restore=restore_plan(enabled=False).replace("ENCRYPT='true'", "ENCRYPT='false'"),
    )

    node.deploy()

    assert node.writes == []


def test_a_forced_restore_without_lxc_restore_applies_notifications_only(node: Node) -> None:
    restore_node(node, enabled=False)

    node.deploy(force=True)

    assert (node.pve / "priv" / "notifications.cfg").is_file()
    assert not (node.pve / "nodes" / "osiris" / "lxc").exists()


def test_missing_credentials_move_on_to_the_next_destination(node: Node) -> None:
    restore_node(node)
    (node.build / "pbs-0.env").write_text("PBS_FINGERPRINT=aa\n")
    token_repo = "osiris-backup@pbs!sync@cottonwood.internal:backup"
    node.stage(
        restore=restore_plan(keyfile=node.m.PERSISTENT_KEYFILE).replace(
            "osiris-backup@pbs@cottonwood.internal:backup", token_repo
        )
    )
    (node.build / "pbs-1.env").write_text('PBS_PASSWORD="pw1"\n')
    node.datastores[token_repo] = [snapshot(1789360205)]

    node.deploy()

    assert node.envs[-1]["PBS_TOKEN_SECRET"] == "pw1"


def test_a_missing_env_file_and_a_failed_restore_both_fail_over(
    node: Node, monkeypatch: pytest.MonkeyPatch
) -> None:
    restore_node(node)
    (node.build / "pbs-0.env").unlink()
    node.datastores["osiris-backup@pbs@cottonwood.internal:backup"] = [snapshot(1789360205)]
    real = node.client
    monkeypatch.setattr(
        node,
        "client",
        lambda argv, kwargs: (
            (1, "", "chunk missing") if argv[1] == "restore" else real(argv, kwargs)
        ),
    )

    with pytest.raises(InstallError, match="No configured PBS destination"):
        node.deploy()


def test_a_differing_existing_config_is_kept_without_force(
    node: Node, capsys: pytest.CaptureFixture[str]
) -> None:
    lxc = node.pve / "nodes" / "osiris" / "lxc"
    lxc.mkdir(parents=True)
    (lxc / "105.conf").write_text("hand edited\n")
    restore_node(node)
    node.stage(
        restore=restore_plan(keyfile=node.m.PERSISTENT_KEYFILE).replace(
            "CONFIG_COUNT='1'", "CONFIG_COUNT='2'"
        )
        + "RESTORE_LXC_CONFIG_1_VMID='111'\n"
    )

    with pytest.raises(InstallError, match="Restored LXC config missing"):
        node.deploy()

    assert "LXC 105 config exists; rerun with --force" in capsys.readouterr().out
    assert (lxc / "105.conf").read_text() == "hand edited\n"
