global_defs {
    script_user nobody
    enable_script_security
}

vrrp_script chk_avail {
    script "/etc/keepalived/healthcheck.sh"
    interval 1
    weight 10
    rise 6
    fall 1
}

vrrp_instance {{ INSTANCE_NAME }} {
    interface {{ INTERFACE }}
    state BACKUP
    virtual_router_id {{ VIRTUAL_ROUTER_ID }}
    priority {{ PRIORITY }}
    advert_int {{ ADVERT_INTERVAL }}

    unicast_src_ip {{ UNICAST_SRC_IP }}
    unicast_peer {
{{ UNICAST_PEERS }}
    }

    virtual_ipaddress {
{{ VIRTUAL_IPS }}
    }

    track_script {
        chk_avail
    }
}
