services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    stop_grace_period: 20s
    networks:
      net.internal: {}
      net_overlay: {}
    restart: always
    mem_limit: 1g
    volumes:
      - /mnt/cache/media/downloads:/data/downloads
      - /mnt/cache/downloads:/downloads
      - /mnt/cache/appdata/prowlarr:/config
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 022
    labels:
      traefik.enable: 'true'
      traefik.http.routers.prowlarr.entryPoints: 'https'
      traefik.http.routers.prowlarr.middlewares: 'allow-local@file'
      traefik.http.services.prowlarr.loadbalancer.server.port: '9696'

networks:
  net.internal:
    external: true
  net_overlay:
    external: true


