services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    stop_grace_period: 20s
    networks:
      net.internal: {}
      net_overlay: {}
    restart: always
    mem_limit: 4g
    
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - 44
      - 107
    
    ports:
      - "8096:8096"
    
    volumes:
      - /mnt/cache/appdata/jellyfin/library:/config
      - /mnt/tank/media:/data:ro
    
    environment:
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: "https://jellyfin.${DOMAIN}"
      TZ: America/New_York
    
    env_file:
      - .env
    
    healthcheck:
      test: curl -f http://localhost:8096/health || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entryPoints: "https"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
      traefik.http.routers.jellyfin.middlewares: "allow-local@file"

networks:
  net.internal:
    external: true
  net_overlay:
    external: true
