[{{ ZFS_POOL }}]
use_template = production
recursive = yes
process_children_only = yes

[{{ ZFS_POOL }}/appdata]
autosnap = no
autoprune = no

[{{ ZFS_POOL }}/backup/appdata]
autosnap = no
autoprune = no

[{{ ZFS_POOL }}/pbs-datastore]
autosnap = no
autoprune = no

[template_production]
hourly = 0
daily = 7
weekly = 4
monthly = 3
yearly = 0
autosnap = yes
autoprune = yes
