Host *
  StrictHostKeyChecking accept-new
  ForwardAgent no

# --- VMs ---
Host helm
  HostName helm.freender.internal
  User freender
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes

Host tower
  HostName tower.freender.internal
  User freender

# --- Baremetal ---

Host exo
  HostName exo.freender.internal
  User freender
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes
  
Host pi-kvm
  HostName pi-kvm.freender.internal
  User root

Host cottonwood
  HostName cottonwood.internal
  User denysc
  
Host cinci
  HostName cinci.internal
  User sysadm

# --- Proxmox nodes ---
  
Host ace
  HostName ace.freender.internal
  User root
  
Host bray
  HostName bray.freender.internal
  User root
  
Host clovis
  HostName clovis.freender.internal
  User root

Host osiris
  HostName osiris.freender.internal
  User root

# --- LXC containers ---

Host xur
  HostName xur.freender.internal
  User root

Host orbit
  HostName orbit.freender.internal
  User root

Host riven
  HostName riven.freender.internal
  User freender
  IdentityAgent /home/freender/.ssh/agent.sock
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes
  ForwardAgent yes
