Host *
  IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Homelab key (VMs / LXCs / baremetal / remote)
Host helm tower exo orbit riven cottonwood cinci pi-kvm
  IdentityFile ~/.ssh/id_ed25519.pub
  IdentitiesOnly yes

# Homelab-Infra key (PVE nodes + PBS)
Host ace bray clovis osiris xur
  IdentityFile ~/.ssh/id_ed25519_pve.pub
  IdentitiesOnly yes

Host riven
  ForwardAgent yes
