[{{ ZFS_POOL }}]
use_template = production
recursive = yes
process_children_only = yes

{{ EXCLUDED_DATASETS }}
[template_production]
hourly = {{ HOURLY }}
daily = {{ DAILY }}
weekly = {{ WEEKLY }}
monthly = {{ MONTHLY }}
yearly = {{ YEARLY }}
autosnap = yes
autoprune = yes
