networks:
  net_overlay:
    external: true

services:
  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.117.1
    user: 1000:1000
    volumes:
      - /mnt/cache/appdata/vmalert/rules:/etc/vmalert/rules:ro
    command:
      - "-datasource.url=http://victoria-metrics:8428"
      - "-notifier.url=http://alertmanager:9093"
      - "-rule=/etc/vmalert/rules/*.yml"
      - "-remoteWrite.url=http://victoria-metrics:8428"
      - "-remoteRead.url=http://victoria-metrics:8428"
    ports:
      - 8880:8880
    restart: always
    mem_limit: 256m
    networks:
      - net_overlay
