networks:
  net.internal:
    external: true
  net_overlay:
    external: true

services:
  victoria-logs:
    container_name: victoria-logs
    image: victoriametrics/victoria-logs:v1.47.0
    user: 1000:1000
    volumes:
      - /mnt/cache/appdata/victoria-logs/data:/victoria-logs-data
    ports:
      - 9428:9428
    command:
      - "-storageDataPath=/victoria-logs-data"
      - "-retentionPeriod=90d"
    restart: always
    mem_limit: 1g
    networks:
      net.internal:
      net_overlay:
